module.exports = [
  'index',
  'esmodule',
  'javascript',
  'javascript-test',
  'javascript-loose',
  'javascript-react',
  'javascript-react-loose',
  'typescript',
  'typescript-test',
  'typescript-declare',
  'typescript-loose',
  'typescript-react',
  'typescript-react-loose',
]
